# Generated by Django 5.0.3 on 2024-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_customers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
