# Generated by Django 5.0.3 on 2025-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_order_num_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_package',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
