# Generated by Django 5.0.3 on 2025-03-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_image',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_slips/'),
        ),
    ]
