# Generated by Django 5.0.3 on 2025-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order_selected_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
